language: python
sudo: required
python: '3.6'

cache:
  - pip

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pipenv run pytest --cov-report term-missing --cov app --capture no

after_success:
  - pipenv run codecov

branches:
  only:
    - master